version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    rebase-strategy: 'auto'
    reviewers:
      - '454de6e'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    rebase-strategy: 'auto'
    reviewers:
      - '454de6e'
